# Checks the format, linting and tsc on all pull requests
name: Check
on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: lts

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Yarn Install
        run: yarn --immutable
      - name: Lint Check
        run: yarn lint:check
      - name: TSC Check
        run: yarn tsc:check
      - name: Prettier Check
        run: yarn prettier:check
